{
CHANNEL_NAME:'mychannel',
USER_NAME:'User1@org1.example.com',
MSPID:'Org1MSP',
PRIVATE_KEY:'./certs/peer/msp/keystore/f1c1261837db43383508cc17aca604076f62e3a72dd33c8c20fe76bbf1ee967e_sk',
SIGN_CERT:'./certs/peer/msp/signcerts/User1@org1.example.com-cert.pem',
PEER_ADDRESS:'peer1.org1.example.com:7051',
PEER_ADDRESS_GRPC:'grpcs://peer1.org1.example.com:7051',
PEER_SSL_TARGET:'peer1.org1.example.com',
ORDERER_SSL_TARGET:'orderer.example.com',
ORDERER_ADDRESS:'grpcs://orderer.example.com:7050',
CHAINCODE_ID:'demo',
CHANNEL_ID:'mychannel',
LISTENING_ADDRESS:'grpcs://orderer.example.com:7053',
BLOCKSIZE:5,
}
